name: Node Test

on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string
      changed:
        required: true
        type: boolean
      node-version:
        required: true
        type: string

jobs:
  run:
    name: Node Test
    if: ${{ inputs.changed }}
    runs-on: ${{ inputs.os }}
    timeout-minutes: 15
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true # Pull submodules for additional files

      - name: Setup Node for Development
        uses: ./.github/actions/setup-node

      - name: Setup Rust
        uses: ./.github/actions/setup-rust
        with:
          tools: just
          cache-key: debug-build

      - name: Build Native Rolldown
        run: just build native

      - name: Type Check
        run: pnpm type-check

      - name: Setup Node for Testing
        uses: ./.github/actions/setup-node
        with:
          node-version: ${{ inputs.node-version }}

      - name: Node Test
        run: pnpm run --recursive --parallel --filter=!rollup-tests test

      - name: Rollup Test
        run: pnpm run --filter rollup-tests test

      - name: examples
        run: pnpm --filter '@example/**' build
